"""Added Student model

Revision ID: 0a19ba1840f0
Revises: 0bf32e1c39a1
Create Date: 2023-11-05 14:53:01.571822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a19ba1840f0'
down_revision = '0bf32e1c39a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
